name: Build Sysmon config with all modules
on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  generate-config:
    runs-on: windows-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Import Merge-SysmonXml.ps1 and generate config
        run: | 
          Import-Module .\Merge-SysmonXml.ps1
          Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml
        shell: pwsh
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: sysmonconfig
          path: sysmonconfig.xml
