name: Build Sysmon config with all modules
on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  generate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Import Merge-SysmonXml.ps1 and generate config
        run: | 
          Import-Module .\Merge-SysmonXml.ps1
          Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml
        shell: pwsh
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sysmonconfig
          path: sysmonconfig.xml
